---
repo-name: peripherals-yammer
categories:
  - messaging
display-name: Yammer
manufacturer: Microsoft
product: Yammer
description: Yammer is a collaboration tool that helps you and your teams stay on top of it all. Start conversations, work together on files, and organize around projects.
